[package]
name = "egui-snarl"
version = "0.1.1"
edition = "2021"
description = "Node-graphs for egui"
license = "MIT OR Apache-2.0"
documentation = "https://docs.rs/egui-snarl"

[features]
serde = ["dep:serde", "egui/serde", "slab/serde"]

[dependencies]
egui = { version = "0.24" }
slab = { version = "0.4" }
serde = { version = "1.0", features = ["derive"], optional = true }

[dev-dependencies]
eframe = { version = "0.24", features = ["serde"] }
egui_extras = { version = "0.24", features = ["all_loaders"] }
syn = { version = "2.0", features = ["extra-traits"] }

[[example]]
name = "demo"
