[package]
name = "egui-snarl"
version = "0.1.0"
edition = "2021"

[features]
serde = ["dep:serde", "egui/serde", "slab/serde"]

[dependencies]
egui = { version = "0.23" }
slab = { version = "0.4" }
lyon_geom = { version = "0.17" }
serde = { version = "1.0", features = ["derive"], optional = true }

[dev-dependencies]
eframe = { version = "0.23", features = ["serde"] }

[[example]]
name = "demo"
required-features = ["serde"]
