[package]
name = "egui-snarl"
version = "0.1.0"
edition = "2021"

[features]
serde = ["dep:serde", "egui/serde", "slab/serde"]

[dependencies]
egui = { version = "0.24" }
slab = { version = "0.4" }
lyon_geom = { version = "1.0" }
serde = { version = "1.0", features = ["derive"], optional = true }

[dev-dependencies]
eframe = { version = "0.24", features = ["serde"] }
egui_extras = { version = "0.24", features = ["all_loaders"] }
syn = { version = "1.0", features = ["extra-traits"] }

[[example]]
name = "demo"
# required-features = ["serde"]
