name: publish

on:
  workflow_dispatch

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/.crates.toml
          ~/.cargo/.crates2.json
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose --all
    - name: Run tests
      run: cargo test --verbose --all
  publish:
    needs: build
    environment:
      name: public
    runs-on: ubuntu-latest
    steps:
    - name: login
      env:
          CARGO_IO_TOKEN: ${{ secrets.CARGO_IO_TOKEN }}
      run: cargo login $CARGO_IO_TOKEN
    - name: publish
      run: cargo publish
